### ISSUE TITLE
Tartini move

### ISSUE THREAD

**Issue by f0rer0** [monarch-initiative/monarch-devops#1]
I know we’re still standing up the new Monarch, but I wanted to start the conversation around what we have to do to move the last machine (tartini) from UCSD to OHSU.

Is there someone we should be talking to about preparing for this move?

Do we have a tentative timeline for when we want this to happen?

**Comment by mellybelly** [comment]
@jgrethe what do we need to do to get things shipped?
Probably in the next few weeks would be ideal as I am sure that Jeff would like to be done with the move.

**Comment by jgrethe** [comment]
Hi Melissa,
Will need to bring Vicky in on this (cc’d above).  There are three things:

1) In terms of getting things shipped - the staff at UCSD will need to unrack and pack the machine for shipping (Vicky anything special that needs to be done here?).

2) In terms of the actual shipment - OHSU will need to contract with a shipper to pick up the machine and deliver it to the facility.

3) In terms of officially moving the machine (i.e. asset transfer) - I have already contacted UCSD and am waiting for an asset transfer letter that will remove from our inventory and add to OHSU.  This letter will be forwarded to OHSU.

Cheers,
Jeff

> On Jan 19, 2016, at 11:01 AM, Melissa Haendel <notifications@github.com> wrote:
> 
> @jgrethe <https://github.com/jgrethe> what do we need to do to get things shipped?
> Probably in the next few weeks would be ideal as I am sure that Jeff would like to be done with the move.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/monarch-initiative/monarch-devops/issues/1#issuecomment-172952368>.
> 


_________________________________________________________________

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu <mailto:jgrethe@ncmir.ucsd.edu>    
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052 <http://crbs.ucsd.edu/>
http://www.linkedin.com/in/jgrethe <http://www.linkedin.com/in/jgrethe>

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by jgrethe** [comment]
Monarch Team,

Tartini is with the vendor at the moment for repair, due to be returned tomorrow.  I’m sure, for a fee, they would be happy to pack up the server and ship it to you, instead.

I know they reinstalled the operating system, so it’s all ready for you to have your way with it.  :-D

-- 
Vicky Rowley

IT Manager
Center for Research in Biological Systems, and the
National Center for Microscopy and Imaging Research

University of California, San Diego
9500 Gilman Dr. MC0608
La Jolla, CA 92093-0608
(858) 822-0708 office
vrowley@ucsd.edu

**Comment by f0rer0** [comment]
If the machine is already offline, then perhaps the best thing is to move it to OHSU now.

Does anyone see any problems with doing this?


David Forero
Technology Director of the Library
Oregon Health and Science University
(503) 494-8692

**Comment by vanmatre** [comment]
Tartini is moved, installed and running at DCW
