### ISSUE TITLE
webphenote not resolving

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-devops#10]
http://create.monarchinitiative.org/

**Comment by vanmatre** [comment]
create.monarchinitiative.org pointed to poole.monarchinitiative.org.

Which of our vm shall I point it to (where is the app running?) Shall it be a cname or a redirect?

**Comment by jnguyenx** [comment]
That would be on monarch2-2 as a cname please.

Thanks!

**Comment by vanmatre** [comment]
Done!

**Comment by jnguyenx** [comment]
Thanks!

Note that the webapp is not up yet, Dan is currently working on deploying
the Noctua stack on this server.

**Comment by jnguyenx** [comment]
Ethan, just to be safe, is it possible to revive the old
create.monarchinitiative.org under a different name?

Like create-old.monarchinitiative.org?

No need to go through the old poole subdomain.

Thanks,
Jeremy

**Comment by vanmatre** [comment]
Of course it is possible to put in create-old  - Where do you want to point it to? The original points to poole (132.239.131.227) Just want to be sure.

--Ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
So I think that we'll have to a cname poole.monarchinitiative.org pointing
to 132.239.131.227, because the services are referring to this url and I
have no access to change that.

Let's try this and see how it goes.

Thanks!

**Comment by vanmatre** [comment]
create-old.monarchinitiative.org  now points to 132.239.131.227 (as an A record). We should likely let them know we are doing this and verify the functionality we need exists.

--ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
Thanks, but we still need a poole.monarchinitiative.org, otherwise the
service will not work.

**Comment by vanmatre** [comment]
OK got it.

poole A 132.239.131.227
create-old CNAME poole



Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
All good! Thanks!
