### ISSUE TITLE
Need monarch-minerva-prod and monarch-barista-prod subdomains pointing to same IP as monarch-noctua-prod

### ISSUE THREAD

**Issue by DoctorBud** [monarch-initiative/monarch-devops#11]
#### What we want

The creation of two new subdomains of monarchinitiative.org:
- monarch-minerva-prod
- monarch-barista-prod

In the short term, both of these domains will point to the same location as monarch-noctua-prod. Longer term, we may scale these services horizontally.

#### Background

The WebPhenote (Monarch's instantiation/customization of Noctua) system consists of three subsystems  (Noctua, Barista, Minerva) which are currently colocated on monarch-noctua-prod. In order for Noctua (the frontend) to work, it needs to be able to communicate from the noctua-delivered web browser page back to a Barista instance via an externally visible URL. This is easily configured via startup.yaml.

However, the nginx proxy running on monarch-noctua-prod needs to be able distinguish port 80 requests intended for Noctua from those intended for Barista. This can be done two ways:
- Specify a subpath /barista in the startup.yaml, and use nginx URL rewriting to remove the /barista prefix before passing it upstream to the colocated barista server.
- Specify distinct domains for Noctua vs Barista in the startup.yaml file. This enables nginx to serve up both domains and direct the requests (by using the server_name field in nginx.conf, I think). No URL rewriting is necessary in this case. This how Noctua is configured at BerkelyBOP.

The second option (subdomains) will be more flexible and easier (for me, at least).

**Comment by vanmatre** [comment]
Done - Minerva and barista set up as CNAMEs in DNS and in the host file for LAN access.

**Comment by DoctorBud** [comment]
Thanks. The new names work as hoped. I'm going to close this ticket.
