### ISSUE TITLE
rename ttl.monarchinitiative.org to data.monarchinitiative.org

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#12]
Apparently that was the original name of this service, I was not aware of that. Sorry!

**Comment by vanmatre** [comment]
NP (No Problem)

ttl.monarchinitiative.org renamed to data.monarchinitiative.org 

ttl and now data are a CNAME that points to monarch-ttl-prod.monarchinitiative.org

**Comment by jnguyenx** [comment]
Thanks!
