### ISSUE TITLE
Can't ping OHSU machines when using monarch domain name

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#13]
monarch-app-beta:~$ ping scigraph-ontology.monarchinitiative.org
never returns.

However when using the OHSU domain name it works:
monarch-app-beta:~$ ping monarch3-3.cslu.ohsu.edu

Is there a reason that we can't do that?

(Note that the same problem applies for monarch-app-prod, monarch-data-load, etc...)

**Comment by jnguyenx** [comment]
I've just realized that Ethan is not here today and tomorrow.

@f0rer0 can you maybe help?

**Comment by TomConlin** [comment]
there is a java process on monarch-data-load that looks "run away" to me (but I just got here) 

sudo ps -u root | grep java
[sudo] ...
14776 ?        1-02:12:12 java <defunct>

it has been using 100% of a cpu for 26 hours now
if it is chewing up network resources it may be the problem

**Comment by jnguyenx** [comment]
Don't really know what that java process is, maybe jenkins.

Anyhow the issue happens on all the servers, I think that it's a DNS or firewall config issue.

**Comment by TomConlin** [comment]
At this point the process is a zombie and very unlikely to be affecting servers other than the one it is on.

**Comment by vanmatre** [comment]
Part of the OHSU security profile prevents a number of "normal" network connections from happening....

I have been setting up host flies to allow internal addresses to resolve but may have missed a few.  DNS to the domain gives the external address of the machines which is (in general) blocked by OHSU security.

If the host files are not working as hoped I can set up the Monarch Domain to use views and have the internal addresses served. This has its' own set of issues (getting permission to run a dns server on the internal network etc).

We can talk about it this week.

--Ethan

**Comment by jnguyenx** [comment]
I see, let's check the host files and see if that works as you think.

I think that this is really needed, because it makes debugging easier for
us. Thanks to the monarch-expressive urls, we can immediately which
services are used.

**Comment by vanmatre** [comment]
I checked the hosts files and found only 1 that was out of date. (Now fixed)

Let me know of any name that does not resolve as expected/needed.

My hope is that the number of names needed to resolve will become static and thus the overhead of keeping host files in sync will be nil. Otherwise, I'll bring up a DNS server views to "solve" this problem.

--ethna


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
Thanks! So I found some other ones:

From monarch-app-beta, cannot ping:

   - beta.monarchinitiative.org (itself)
   - solr-dev.monarchinitiative.org

from monarch-data-load, cannot ping:

   - data.monarchinitiative.org

from monarch-app-prod:

   - monarchinitiative.org (itself)
   - scigraph-ontology.monarchinitiative.org
   - scigraph-data.monarchinitiative.org
   - solr.monarchinitiative.org
   - mme.monarchinitiative.org
   - create.monarchinitiative.org

For now it's all that we need to resume our releases and development.

**Comment by vanmatre** [comment]
Ah, Those are the CNAMES we created. I've placed them in the hosts file. "shoule" all be working now.

-Ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________
