### ISSUE TITLE
Can't access data server from monarch-data-load

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#16]
From the machine monarch-data-load, I'd like to download a file from http://data.monarchinitiative.org/ttl/wormbase.nt.

wget directly this url works.

In a java application, the url is resolved to the IP first, and for some reason the wget does not work anymore.

jenkins@monarch-data-load:~/ontology-graph$ wget http://137.53.238.98/ttl/wormbase.nt
--2016-02-09 14:15:39--  http://137.53.238.98/ttl/wormbase.nt
Connecting to 137.53.238.98:80... failed: Connection timed out.

**Comment by vanmatre** [comment]
More OHSU security at work. Resolving the hostname via DNS gives the external address (137.53.238.98) and wget to the FQDN is allowed past the firewalls (and websense) however port 80 access to an IP address it blocked when traversing the firewall.

If you can use the internal address (10.95.40.132 from the host file) you "should" be able to get the data you want.

--Ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
Right, that's not very convenient.

The issue being that the application which downloads the files need to run
also outside OHSU. So if I configure it to use the internal address, it'll
work at OHSU but not on my laptop. And vice-versa.

So is there any chance to harmonize that and use an address reachable both
from inside and outside?

**Comment by vanmatre** [comment]
Very unlikely to change firewall/security here....

OK, So I'll have to set up an views based DNS server which will serve internale address to internal machines and external addresses to external requests.

It could take a day or few.

--Ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
@vanmatre Any updates on the DNS view?

**Comment by vanmatre** [comment]
None yet. I'm working on "stuff" for my other job. 40% jobshare to Monarch - I neglected the other 60% for the last month or so....

**Comment by jnguyenx** [comment]
Now that we have the DNS views, what's the canonical url to access an OHSU VM?

Let's that that I'm logged in monarch-data-load, and I want to access the monarch-solr-prod solr. What is the preferred address to ssh in that VM?
137.53.238.95, monarch2-1.cslu.ohsu.edu or other?

**Comment by vanmatre** [comment]
(no views on the DNS)

from any monarch VM you wold just use the host name (monarch-solr-prod) or the short name (solr). You could even use the OHSU name (monarch2-1). All of these are in the monarchinitiative.org >>internal<< DNS (solr.monarchinitiative.org) and only work from the monarch machines.

If you use the cslu.ohsu.edu domain (solr.cslu.ohsu.edu) you will get the >>external<< DNS address

Hope that helps.

In any case here is the zone file extract for the addresses:

; Base metal - physical servers
;
monarch1        IN    A    10.95.40.101
monarch2        IN    A    10.95.40.102
monarch3        IN    A    10.95.40.103
monarch4        IN    A    10.95.40.104
monarch5        IN    A    10.95.40.105
;
;
;
;
; VM running on monarch1
;
monarch-app-prod    IN    A    10.95.40.111
monarch-mme-prod    IN    A    10.95.40.112
monarch-app-beta    IN    A    10.95.40.113
gray-log        IN    A    10.95.40.114

;
; VM running on monarch2
;
monarch-solr-prod    IN    A    10.95.40.121
monarch-noctua-prod    IN    A    10.95.40.122
monarch-solr-dev    IN    A    10.95.40.123
genome            IN    A    10.95.40.124

;
; VM running on monarch3
;
scigraph-ontology-prod    IN    A    10.95.40.131
monarch-ttl-prod    IN    A    10.95.40.132
scigraph-ontology-dev    IN    A    10.95.40.133
;
; VM running on monarch4
;
scigraph-data-prod    IN    A    10.95.40.141
monarch-access        IN    A    10.95.40.142
vm-monitor        IN    A    10.95.40.143
scigraph-data-dev    IN    A    10.95.40.144
monarch-data-load    IN    A    10.95.40.145
vm1-openrif        IN    A    10.95.40.146
;
; VM running on monarch5
;
owlsim            IN    A    10.95.40.151
owlsim3            IN    A    10.95.40.152
ns1            IN    A    10.95.40.153
;
;
; CNAMES and other pointers
;
www            IN    CNAME    monarch-app-prod
;
beta            IN    CNAME    monarch-app-beta
create            IN    CNAME    monarch-noctua-prod
data            IN    CNAME    monarch-ttl-prod
mme            IN    CNAME    monarch-mme-prod
monarch-barista-prod    IN    CNAME    monarch-noctua-prod
monarch-minerva-prod    IN    CNAME    monarch-noctua-prod
noctua            IN    CNAME    monarch-noctua-prod
scigraph-data        IN    CNAME    scigraph-data-prod
scigraph-ontology    IN    CNAME    scigraph-ontology-prod
solr            IN    CNAME    monarch-solr-prod
solr-dev        IN    CNAME    monarch-solr-dev
;
; (dot) cslu.ohsu.edu names
;
monarch1-1        IN    A    10.95.40.111
monarch1-2        IN    A    10.95.40.112
monarch1-3        IN    A    10.95.40.113
monarch1-4        IN    A    10.95.40.114
;
monarch2-1        IN    A    10.95.40.121
monarch2-2        IN    A    10.95.40.122
monarch2-3        IN    A    10.95.40.123
monarch2-4        IN    A    10.95.40.124
;
monarch3-1        IN    A    10.95.40.131
monarch3-2        IN    A    10.95.40.132
monarch3-3        IN    A    10.95.40.133
;
monarch4-1        IN    A    10.95.40.141
monarch4-2        IN    A    10.95.40.142
monarch4-3        IN    A    10.95.40.143
monarch4-4        IN    A    10.95.40.144
monarch4-5        IN    A    10.95.40.145
monarch4-6        IN    A    10.95.40.146
;
monarch5-1        IN    A    10.95.40.151
monarch5-2        IN    A    10.95.40.152
monarch5-3        IN    A    10.95.40.153


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
That makes sense, thank you for clarifying that!
