### ISSUE TITLE
requisition a new machine

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/monarch-devops#19]
I would like a machine available:

http://genome.monarchinitiative.org

Specs:  4 processors, 12 GB RAM, 200 GB of disk space

@jnguyenx  said he will give me access

**Comment by vanmatre** [comment]
The vm has been created. genome.monarchinitiative.org (monarch2-4.cslu.ohsu.edu)
Will we need access outside of the internal network?

**Comment by jnguyenx** [comment]
Normally only port 80 will be needed for this now.

Thanks for the fast support!

**Comment by nathandunn** [comment]
Ditto.  Thanks.

**Comment by jnguyenx** [comment]
It seems that the VM is not connected to internet at all:

$ sudo apt-get update
Err http://security.ubuntu.com trusty-security InRelease

Err http://security.ubuntu.com trusty-security Release.gpg
  Could not resolve 'security.ubuntu.com'
Err http://us.archive.ubuntu.com trusty InRelease

Err http://us.archive.ubuntu.com trusty-updates InRelease

Err http://us.archive.ubuntu.com trusty-backports InRelease

Err http://us.archive.ubuntu.com trusty Release.gpg
  Could not resolve 'us.archive.ubuntu.com'
Err http://us.archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'us.archive.ubuntu.com'
Err http://us.archive.ubuntu.com trusty-backports Release.gpg
  Could not resolve 'us.archive.ubuntu.com'
Reading package lists... Done
W: Failed to fetch
http://us.archive.ubuntu.com/ubuntu/dists/trusty/InRelease

W: Failed to fetch
http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease

W: Failed to fetch
http://us.archive.ubuntu.com/ubuntu/dists/trusty-backports/InRelease

W: Failed to fetch
http://security.ubuntu.com/ubuntu/dists/trusty-security/InRelease

W: Failed to fetch
http://security.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could
not resolve 'security.ubuntu.com'

W: Failed to fetch
http://us.archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not
resolve 'us.archive.ubuntu.com'

W: Failed to fetch
http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could
not resolve 'us.archive.ubuntu.com'

W: Failed to fetch
http://us.archive.ubuntu.com/ubuntu/dists/trusty-backports/Release.gpg
Could not resolve 'us.archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones
used instead.

**Comment by vanmatre** [comment]
Fixed! - resolver not set up properly.

**Comment by jnguyenx** [comment]
Thanks!

We're almost there, the domain names cannot be resolved:
jnguyenxuan@M3800:~$ curl genome.monarchinitiative.org
curl: (6) Could not resolve host: genome.monarchinitiative.org
jnguyenxuan@M3800:~$ curl monarch2-4.cslu.ohsu.edu
curl: (6) Could not resolve host: monarch2-4.cslu.ohsu.edu

**Comment by vanmatre** [comment]
Question: Will genome need access from outside OHSU? It currently does not have an external address only the internal address.

**Comment by jnguyenx** [comment]
Yes only port 80 is needed.

**Comment by jnguyenx** [comment]
@vanmatre Any updates on this server?

**Comment by vanmatre** [comment]
genome.monarchinitiave.org has an external address with ports 80 and 443 open externally. (no ssh)

DNS points to the external address, files point to the internal address.

**Comment by nathandunn** [comment]
Hmmm .. .. internally we can do:

curl localhost:80/apollo/annotator/index

and get the proper result.  

Externally we don’t seem to resolve:

curl http://genome.monarchinitiave.org/apollo/annotator/index/ <http://genome.monarchinitiave.org/apollo/annotator/index/>

curl: (6) Could not resolve host: genome.monarchinitiave.org


Nathan

**Comment by jnguyenx** [comment]
http://genome.monarchinitiative.org/apollo/annotator/index

It has just started working for me.

However there's still a issue with the nginx conf,
http://genome.monarchinitiative.org/apollo redirect to a weird url. Can you
have a look Nate?

**Comment by vanmatre** [comment]
Spelling on the url (monarchinitiative)

from offsite:

# curl genome.monarchinitiative.org:80/apollo/annotator/index
<!DOCTYPE html>



Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by nathandunn** [comment]
Doh . . thanks.

**Comment by nathandunn** [comment]
I'll take a look at that internal redirect.  . thanks.

**Comment by nathandunn** [comment]
@jnguyenx  We need to add this line to the apollo-config.groovy

```grails.serverURL = "https://genome.monarchinitiative.org/apollo/"```

It is doing a redirect internally, but I think that it must have the wrong default host.  

If you point me to the proper file I can edit it.

**Comment by jnguyenx** [comment]
https://github.com/monarch-initiative/monarch-devops/blob/master/ansible/ohsu-migration/roles/apollo/files/apollo-config.groovy

Once you do that I'll repackage the app.

**Comment by nathandunn** [comment]
Okay I added it here: #21 

Should I begin adding files or do you have to rebuild the machine?

**Comment by nathandunn** [comment]
Also added #22 to update the RC1 to RC2 . . .
