### ISSUE TITLE
Additional VMs for Dev and Beta environments

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#2]
For the Beta environment, only one VM is needed:
* monarch-app-beta

For the Dev:
* monarch-solr-dev
* scigraph-ontology-dev
* scigraph-data-dev

We'll need a dedicated machine for loading data, that's a long and hungry process.
* monarch-data-load,(500GB minimum ( or 1TB to be confortable) & as much CPU and RAM possible

**Comment by vanmatre** [comment]
Are these VM in addition to the 4 "stage" VM we talked about friday?

**Comment by jnguyenx** [comment]
No, those 5 VMs are what we need for our beta+dev environment.

Basically we renamed stage to beta, beta to dev and slimmed down the beta
to a single VM.

**Comment by vanmatre** [comment]
All additional VM have been created. Their external address have been entered into DNS. In addition there are 2 more entries in DNS: vm-monitor.monarchinitiative.org and ohsu-www.monarchinitiative.org which is a cname for monarch-app-prod.

vm-monitor.monarchinitiative.org/ganglia and .../nagios are active. Let me know if you want a nagios login.

Attached please find a spreadsheet of the VM, their addresses and their specs (cores, ram,disk)

[monarch-provision (3)-2-1.xlsx](https://github.com/monarch-initiative/monarch-devops/files/103629/monarch-provision.3.-2-1.xlsx)

**Comment by cmungall** [comment]
Thanks for the spreadsheet @vanmatre -- should we track this using git, dropbox, ...?

**Comment by jmcmurry** [comment]
@vanmatre, please let's use a tab file in git instead.
