### ISSUE TITLE
Share VMs list on GoogleDocs

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#29]
For reference purpose, share the updated spreadsheet from https://github.com/monarch-initiative/monarch-devops/issues/2 in GoogleDocs

**Comment by vanmatre** [comment]
https://docs.google.com/spreadsheets/d/1VteU83L2rS9yHs6RlsUyZDf_-0inJ1IEfHt2FZqlNEM/edit?usp=sharing

**Comment by jnguyenx** [comment]
Thanks!

Is it up to date though? I don't see the genome vm for example.

**Comment by vanmatre** [comment]
Not likely to be up to date. Latest I could find on the email exchanges wiith our ITG. I thought to update it online.



Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by vanmatre** [comment]
I've added in genome.

 As part o fthe review I see that the old monarch-solr-dev is running. Do we need this VM anymore? If not I'll shut it down.

--Ethan



Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
Thanks. We don't use that VM, you can shut it down.
