### ISSUE TITLE
New VM for log centralization

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#30]
I originally planned to install GrayLog on the monarch-access VM, but I'd prefer to have a dedicated machine for that.

Some consideration to take performance wise:
http://docs.graylog.org/en/1.3/pages/architecture.html

For us I would aim for that:

- 4 cores
- 8GB ram
- 64GB disk space

Port 80 will need to be exposed.

**Comment by vanmatre** [comment]
Almost done with the new VM....

**Comment by vanmatre** [comment]
gray-log VM has been created and is ready for the adding of applications. 

Let me know if you find any problems.

--Ethan

10.95.40.114    monarch1-4.cslu.ohsu.edu monarch1-4     gray-log gray-log.monarchinitiative.org

**Comment by jnguyenx** [comment]
Thanks!
