### ISSUE TITLE
redirect www to non-www

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#34]
https://www.monarchinitiative.org should redirect to https://monarchinitiative.org. The first one fails due to certs. In any case it's better to have a canonical URL.

I believe that this is a godaddy configuration.

**Comment by vanmatre** [comment]
At godaddy www.monarchinitiative.org was a cname pointed to monarch-app-prod.monarchinitiative.org.

I have changed this to point to @ (which is monarchinitiative.org) thus

www.monarchinitiative.org points to monarchinitiative.org which has the address of monarch-app-prod.monarchinitiaive.org.

I'm not sure that this will take care of the cert issue but let's see.

**Comment by jnguyenx** [comment]
I don't think that the forwarding is currently working.

I've done redirecting from non-www to www, but not the other way around. In any case, the setup was using a GoDaddy IP to do the redirection.

https://www.godaddy.com/help/manually-forwarding-or-masking-your-domain-name-422

I'm not sure, but I think that @ should point to 50.63.202.1, but then I don't know how to point monarchinitiative.org to monarch-app-prod.monarchinitiative.org.

**Comment by harryhoch** [comment]
thanks, @jnguyenx  -  I couldn't reopen this one. What can be done to get this fixed?

**Comment by jnguyenx** [comment]
It has not be solved yet. It's a GoDaddy configuration issue, you can redirect www to non-www and vice versa.

@vanmatre did you have the time to look at this again?

**Comment by vanmatre** [comment]
yes, I'll do some checking.

**Comment by vanmatre** [comment]
I've done some checking of the cert and found that there are no alternate names listed in the cert (the cert for monarchinitiative.org could include an alternative name of www.monarchinitiative.org). See the results of testing in the next post by me.

I've also looked at GoDaddy and attempted to change how it "translates" www.monarchinitiative.org into monarchinitiative.org. Once the TTL expires we will be able to test (at least for those who have cached lookups)

--ethan

**Comment by vanmatre** [comment]
Testng:

for www.monarchinitiative.org

None of the common names in the certificate match the name that was entered (www.monarchinitiative.org). You may receive an error when accessing this site in a web browser. Learn more about name mismatch errors.

for monarchinitiative.org

all OK

for monarch-app-prod.monarchinitiative.org

None of the common names in the certificate match the name that was entered (monarch-app-prod.monarchinitiative.org). You may receive an error when accessing this site in a web browser. Learn more about name mismatch errors.

Here is a brief description:

The name mismatch error indicates that the common name (domain name) in the SSL certificate doesn't match the address that is in the address bar of the browser. For example, if the certificate is for www.paypal.com and you access the site without the "www" (https://paypal.com), you will get this SSL certificate name error. If you aren't the website administrator you will want to always access the site with the full name (usually include the "www." before the domain name) or ask the website owner to fix the problem.

If you are the website administrator, you will usually want to forward all traffic without the "www" to an address with the "www" and get an SSL certificate with the "www" in the common name. That way you will completely avoid the name mismatch error. Some certificate authorities get around this problem by issuing a certificate with SANs. So you can get a certificate for paypal.com and include a SAN of www.paypal.com so you don't get a name mismatch error. Another common reason for this error is if you are accessing a server using an internal name when the SSL certificate on it just has the public name on it. In this situation you can get a UC certificate that has both the external public name and the internal server name in the certificate. You can verify whether you will get a name mismatch error by using our SSL Checker.

-----------------

Another checker givers the same results. See: https://www.ssllabs.com/ssltest/analyze.html?d=www.monarchinitiative.org

The base problem is that we should have both monarchinitiative.org and www.monarchinitiative.org inthe cert. Getting it reissued with the alternate name (now or when it expires in 6 months) is a solution.

Here are some of the results for www.monarchinitiative.org

Server Key and Certificate #1
Subject monarchinitiative.org
Fingerprint SHA1: 906b74a88e709981a476ff289d26503adf697dc9
Pin SHA256: qpulAOVKnbKIJAaEXR6UFOfg8/K7I0fXEjFi6+CbbU8=
Common names    monarchinitiative.org   MISMATCH
Alternative names       monarchinitiative.org
Valid from      Thu, 19 May 2016 22:20:00 UTC
Valid until     Wed, 17 Aug 2016 22:20:00 UTC (expires in 2 months and 28 days)
Key     RSA 2048 bits (e 65537)
Weak key (Debian)       No
Issuer  Let's Encrypt Authority X3
AIA: http://cert.int-x3.letsencrypt.org/
Signature algorithm     SHA256withRSA
Extended Validation     No
Certificate Transparency        No
Revocation information  OCSP
OCSP: http://ocsp.int-x3.letsencrypt.org/
Revocation status       Good (not revoked)
Trusted No   NOT TRUSTED (Why?)

**Comment by vanmatre** [comment]
Of course, this breaks www.monarchinitiative.org till the redirect takes effect..... I'll keep an eye on it and put the cname for www back in if it does not resolve in the next 30 minutes or so.

**Comment by vanmatre** [comment]
looks to be redirecting now.

**Comment by jnguyenx** [comment]
Perfect thanks!

On a side not: I agree that adding www.monarchinitiative.org in the ssl can fix the problem, but I don't think that it's the right fix. As stated in my first comment, having a canonical url is a good practice, especially for SEO purposes.
