### ISSUE TITLE
Switch from Host files to local DNS server

### ISSUE THREAD

**Issue by vanmatre** [monarch-initiative/monarch-devops#35]
I have brought up a DNS server serving monarchinitiative.org internal addresses. This is running on monarch5-3.cslu.ohsu.edu (a VM on the old tartini - monarch5). I plan on having GoDaddy serve address to lookups originating outside of the monarch systems and the DNS server serving addresses to the other monarch machines.

This means that access to the monarch systems from all non-monarch servers will be like it is now. And that all access from a monarch system will get an OHSU internal address from the nameserver.

I have tested the nameserver and it resolves addresses correctly but I did want to give heads up before switching over from host files to DNS.

I plan on switching over Thursday morning at 10 am - keep an eye out for anything that breaks and of course let me know if there is a better time to cutover.

--Ethan

**Comment by jnguyenx** [comment]
Thanks Ethan, tomorrow 10am works for me! I'll keep an eye.
