### ISSUE TITLE
Move HPO site to OHSU servers

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-devops#38]
@pnrobinson requested that we host this in our new infrastructure for ease of sys admin among other things.
@drseb can you help describe what exists and what needs to be done?
@jnguyenx @cmungall can also assist.

**Comment by drseb** [comment]
First I would like to have more information regarding the context of this. Not sure which sites should move and what the reasons are.

**Comment by cmungall** [comment]
Wait, it's github pages. The sys admin costs to Charite are $0.00. I think there must have been a miscommunication somewhere, I suggest closing this ticket.

**Comment by drseb** [comment]
I guess this was about Exomiser. Sanger won't host anymore.

**Comment by mellybelly** [comment]
@julesjacobsen @damiansm let us know if you need anything moved; perhaps @pnrobinson was referring to the hudson build? I am uncertain, but we are happy to help if there is a need.

**Comment by drseb** [comment]
ok. waiting for @pnrobinson to clarify

**Comment by pnrobinson** [comment]
There are yet more various new developments - let's hold off on this for a bit and make plans for the medium term!

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor of Bioinformatics, Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Melissa Haendel [notifications@github.com]
Gesendet: Freitag, 6. Mai 2016 12:24
An: monarch-initiative/monarch-devops
Cc: Robinson, Peter; Mention
Betreff: Re: [monarch-initiative/monarch-devops] Move HPO site to OHSU servers (#38)


@julesjacobsen<redir.aspx?REF=ZJPs9owH-gKZiPFRRFjOU8WpjBVgsW4xjMsae5taGZf2W09wrXXTCAFodHRwczovL2dpdGh1Yi5jb20vanVsZXNqYWNvYnNlbg..> @damiansm<redir.aspx?REF=AEOFQYTSxMVnyaz671dhXDF8dSssCZmUwrfXfIiv0vn2W09wrXXTCAFodHRwczovL2dpdGh1Yi5jb20vZGFtaWFuc20.> let us know if you need anything moved; perhaps @pnrobinson<redir.aspx?REF=PeExsTHkm0Mszamdv-IG-f0pkU_ytbslbLEk2vdS2B72W09wrXXTCAFodHRwczovL2dpdGh1Yi5jb20vcG5yb2JpbnNvbg..> was referring to the hudson build? I am uncertain, but we are happy to help if there is a need.

**Comment by mellybelly** [comment]
Ok I will close, but please feel free to let us know if you need anything in this regard.
