### ISSUE TITLE
Migrate domain name to OHSU servers

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#4]
Note: I'm still having some issues with nginx

http://monarchinitiative.org = http://monarch1-1.cslu.ohsu.edu

http://owlsim.monarchinitiative.org = http://monarch1-1.cslu.ohsu.edu/owlsim/

http://solr.monarchinitiative.org = http://monarch2-1.cslu.ohsu.edu/

http://noctua.monarchinitiative.org = http://monarch2-2.cslu.ohsu.edu/

http://scigraph-ontology.monarchinitiative.org = http://monarch3-1.cslu.ohsu.edu/

http://scigraph-data.monarchinitiative.org = http://monarch4-1.cslu.ohsu.edu/

http://ttl.monarchinitiative.org = http://monarch3-2.cslu.ohsu.edu/

**Comment by vanmatre** [comment]
Domain root changed to monarch1-1.cslu.ohse.udu (137.53.238.93 - monarch-app-prod)

The others were created as CNAMES pointing to their respective prod vm as requested.

N.B. olwsim just points to the monarch app-prod VM.

www.monarchinitiative.org now points to monarch-app-prog.

TTL is 1 hour.

**Comment by jnguyenx** [comment]
Is there anyway to use redirect instead of cnames to have owlsim.monarchinitiative to point to http://monarch1-1.cslu.ohsu.edu/owlsim/ ?

Here are more subdomain to create please:

http://beta.monarchinitiative.org/ =  http://monarch1-3.cslu.ohsu.edu/

http://solr-dev.monarchinitiative.org/ = http://monarch2-3.cslu.ohsu.edu/

http://scigraph-ontology-dev.monarchinitiative.org = http://monarch3-3.cslu.ohsu.edu/

http://scigraph-data-dev.monarchinitiative.org = http://monarch4-4.cslu.ohsu.edu/

**Comment by jnguyenx** [comment]
Nice for owlsim.monarchinitiative.org. Is it possible to just remove the trailing / in the redirect? Our app does not like that...

**Comment by jnguyenx** [comment]
All good now, thanks!
