### ISSUE TITLE
update apollo to 2.0.3

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/monarch-devops#40]
https://github.com/GMOD/Apollo/tree/2.0.3 . . .

**Comment by nathandunn** [comment]
@jnguyenx   What would be the easiest way to do this?  The script is almost identical but we install node.js, bower, and a different version of Apollo.  

These are the users' to add, which includes the reviewer:

<img width="573" alt="screen shot 2016-06-28 at 11 50 56 am" src="https://cloud.githubusercontent.com/assets/751274/16422508/ab52aad4-3d26-11e6-8b3b-816a1f83585a.png">

The reviewer has access to mouse, human, and zebrafish.

**Comment by nathandunn** [comment]
@jnguyenx  I can edit and create a PR if that is the way to go.   This isn't urgent, but would like to do it as we have time.

**Comment by jnguyenx** [comment]
Yes you can do a PR to update the apollo version here:
https://github.com/monarch-initiative/monarch-devops/blob/master/ansible/jenkins/apollo.yml

For the users, I assume that it is just a file on the server to change, can you do that manually?

**Comment by nathandunn** [comment]
2.0.4 seems to be sensible and working!

**Comment by nathandunn** [comment]
A quick note on updates (if we ever have to do this again) for @kltm  / @kshefchek / @monicacecilia etc. 

1 - update version in ansible script: 

https://github.com/monarch-initiative/monarch-devops/blob/67a4b4d1c7e0111954fd328182fbcb496dbfb158/ansible/jenkins/apollo.yml

2 - rerun jenkins: 

http://ci.monarchinitiative.org/view/prod/job/start-apollo-prod/

3 - check if the right version: 

https://genome.monarchinitiative.org/apollo/version.jsp

4 - test 'admin@admin.com':

https://genome.monarchinitiative.org/apollo/

login to fix / scour is:  monarch4-2.cslu.ohsu.edu / genome 

@jnguyenx  Please feel free to remove any of this info if you think it should not be public and thanks for doing this.
