### ISSUE TITLE
scigraph-data-prod needs more diskspace 

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#41]
See #37 

> monarch@scigraph-data-dev:/tmp$ df -h
> Filesystem                       Size  Used Avail Use% Mounted on
> udev                              32G  4.0K   32G   1% /dev
> tmpfs                            6.3G  436K  6.3G   1% /run
> /dev/vda3                        119G  113G   26M 100% /
> none                             4.0K     0  4.0K   0% /sys/fs/cgroup
> none                             5.0M     0  5.0M   0% /run/lock
> none                              32G  996K   32G   1% /run/shm
> none                             100M     0  100M   0% /run/user
> /dev/vda1                        232M   37M  179M  18% /boot
> monarch4:/disk/vmpartition/data   22T  2.8T   18T  14% /mnt/data

**Comment by vanmatre** [comment]
How much disk space do you want to see on scigraph-data-prod?

We are currently using 2.8 TB on the NFS mount filesystem. (PS it can be locked down further is needed permissions wise).

The path of least resistance is to build a new VM with the disk space you need and then swap it onto production when it is ready to go. I will use LVM which will allow disk expansion.

--Ethan
 

evm@scigraph-data-prod:~$ df -h
Filesystem                       Size  Used Avail Use% Mounted on
udev                              31G  4.0K   31G   1% /dev
tmpfs                            6.2G  424K  6.2G   1% /run
/dev/vda3                        111G  103G  3.0G  98% /
none                             4.0K     0  4.0K   0% /sys/fs/cgroup
none                             5.0M     0  5.0M   0% /run/lock
none                              31G  768K   31G   1% /run/shm
none                             100M     0  100M   0% /run/user
/dev/vda1                        232M   70M  146M  33% /boot
monarch4:/disk/vmpartition/data   22T  2.8T   18T  14% /mnt/data

**Comment by jnguyenx** [comment]
Ok let's do the re-install late next week, as we currently need our dev services to test new data.

**Comment by vanmatre** [comment]
If we could allocate more ram for a ram disk how much would be needed? (and cpu also)

**Comment by jnguyenx** [comment]
That machine just need more disk space, and won't need ram disk. Since this
is a production VM, we'll need to coordinate to minimize the downtime.

**Comment by vanmatre** [comment]
How big should we make the new VM disk? The NFS partition is currently using 2.8 TB.

**Comment by jnguyenx** [comment]
Let's go with 0.5TB for the long run.

Remember that this is a production VM.
