### ISSUE TITLE
New VM request for plain Neo4j server

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#42]
neo.monarchinitiative.org

8 cores
128GB ram (If we're short on ram 64GB ram is sufficient)
500GB disk space, so we can use this machine for other experiments

Port 80 will need to be exposed.

**Comment by vanmatre** [comment]
Do have a specific server you want it on of shall I pick one?

**Comment by jnguyenx** [comment]
Any server is fine, thanks!

**Comment by vanmatre** [comment]
OK - I'm doing the math now for available resources. Which VM would you like a ramdisk on? I can allocate more ram in some cases.

**Comment by jnguyenx** [comment]
That would be for monarch-data-load, after we move it to the baremetal with
SSDs.

But before going into ramdisk, how big can this partition be? I think that
we'll need at least 100GB, and if possible 200GB to be more comfortable.

**Comment by vanmatre** [comment]
tell me about monarch5-4 - know anything?

**Comment by jnguyenx** [comment]
That's the initial VM to test out the SSDs, which ran out of disk space. We
can get rid of it.

**Comment by vanmatre** [comment]
neo4j.monarchinitiative.org is now running on monarch3-4.  The external address has not been assigned as of yet but you can get to it from the other monarch VM.

**Comment by jnguyenx** [comment]
Can you please add me as sudo?

**Comment by vanmatre** [comment]
Done!

Sorry about forgitting to do that.

-_Ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
One last thing, I ran out of disk space, there's only 9G available.

**Comment by vanmatre** [comment]
Yes, the setup on this VM with LVM is a bit off. The default is to put the space in /home. (there is 92 GB there). Can you set up links to /home or shall I rebuild the VM?

Where do you normally place your working directories?

**Comment by jnguyenx** [comment]
I see, I think that the best practice is to put custom stuff in /opt and
/var and not in the /home of a particular user.

I would rather keep doing this way. Can you please go ahead and rebuild the
VM?

Thanks!

**Comment by vanmatre** [comment]
Will do. Just have to force the installer to partition LVM like we want...



Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by vanmatre** [comment]
OK, a new VM is created and is ready to be worked on. You are in the sudo file.

**Comment by jnguyenx** [comment]
I can't connect to the VM for some reason, I tried my username and also the
monarch one. I don't think that the access file has been copied over.

And while we're at it, I think that from now on we can use Ubuntu 16.04,
since we're going to reinstall most of the VMs to have LVM. Sorry for not
thinking about that earlier...

**Comment by vanmatre** [comment]
Can do (ubuntu 16). I'm sure that you are aware that there are major changes between 14 and 16. 

IT has not set up the external access so we can only access neo4j from another monarch VM.

Given the delay in getting outside access we have time to reload it with ubuntu 16. What do you think?

**Comment by vanmatre** [comment]
Ah, got it. Corrupt shadow file entry. Fixed

**Comment by jnguyenx** [comment]
Yep let's reload to 16! Thanks Ethan!

**Comment by vanmatre** [comment]
OK will get going on it today.

**Comment by vanmatre** [comment]
the VM has been created with Ubuntu 16.01.1 LTS. Users, sudo are set and we did get the outside address configured. Onlu http and https are open from the outside.

--Ethan

**Comment by jnguyenx** [comment]
Many thanks, the service is up and running!

http://neo4j.monarchinitiative.org/

**Comment by jnguyenx** [comment]
@vanmatre can you please update the googledocs and add this server?
Thanks!

**Comment by vanmatre** [comment]
Got a more direct link to the doc? I'm not finding it

**Comment by jnguyenx** [comment]
https://docs.google.com/spreadsheets/d/1VteU83L2rS9yHs6RlsUyZDf_-0inJ1IEfHt2FZqlNEM/edit#gid=168336483

**Comment by vanmatre** [comment]
There it is.
