### ISSUE TITLE
Move monarch-data-load to old Tartini

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#43]
As discussed by email, let's move this VM to the SSD machine.

(Moving the VM would be ideal, but we can also consider a fresh new install, that would require more coordination though.)

**Comment by jnguyenx** [comment]
@vanmatre do you have any time estimate for that? We could really use some more disk I/O for our data pipeline.

**Comment by vanmatre** [comment]
I'll be able to work on it this week. I had some hardware fires last week)

Ethan

**Comment by vanmatre** [comment]
Is there a time I can shut down Monarch-data-load ? We will need to shut it down to clone it over. It could be down for a day.

**Comment by jnguyenx** [comment]
So tomorrow will be ideal for us! Thanks!

**Comment by vanmatre** [comment]
Sounds good - So the plan is to shut it down sometime in the AM on Wednesday 9/14 and get it up asap (could be 24 hours)



Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by vanmatre** [comment]
Of course there is a snag....

The target physical server Monarch5 (tartini) has 207 GB free disk space. There is an old VM (monarch5-4) running (last logged into by Jeremy on 9/11) that will free up 500 gb disk hen deleted giving us around 700 GB free disk.

Monarch-data-load is currently set for 1 TB of disk - Not enough free disk space to clone the VM over to Monarch5.

Options include creating a new VM on monarch5 that will fit into the existing disk space and loading what software you need to moke it into monarch-data-load.

Another option is to take the existing vm (monarch5-4) and turn it into monarch-data-load with 500 GB disk.

Monarch5 dies have ssd disks but the total size for those disks is 1.1 TB.

Another option is to replace the SSD disks (at cost) to have SSD of larger capacity.

Even with moving the other VM off Monarch5 to free up space we still have only 1.1TB disk so only 1 VM would fit (with a 1 TB disk)

Please advise

**Comment by jnguyenx** [comment]
I would decommision monarch5-4, move the rest of the VMs on monarch5 (owlsim, owlsim3, ns1) elsewhere, and use tartini directly as a baremetal, without any VM layer.

How does that sound? Hopefully 1TB is enough for our Jenkins CI stuff.

**Comment by vanmatre** [comment]
That is OK  - I'll start work on it.

**Comment by vanmatre** [comment]
Just finished up moving the VM on manarch5 to other systems.  Please do check owlsim and owlsim3 to be sure that they are running any apps you expect them to do.

I did notice that there was a java process that @jnguyenx owned that was running before the move and not after. It had been running for quite some time.

I'll finish up on monarch5 tomorrow so that we can host monarch-data-load there.

**Comment by jnguyenx** [comment]
We were using those for experiments so far and haven't deployed any production apps. So do not worry for those processes.

**Comment by vanmatre** [comment]
Next question... How long could monarch-data-load be down for? Could it be down over the weekend?

**Comment by jnguyenx** [comment]
Hmm why do you need to shut it down for? I thought that it'll be just a
CNAME switch when we have installed the services on Tartini no?

**Comment by vanmatre** [comment]
I was wondering so that I could take a snapshot. In thinking about a snapshot I realized that because of its size getting a snapshot could take quite some time. _ planning ahead.

**Comment by jnguyenx** [comment]
Oh okay I see, well we can do the snapshot after we have done the move, I
don't think that there's any risk to lose our data before moving right?

**Comment by vanmatre** [comment]
The current monarch 5 Hardware is running Ubuntu 14.04.5 LTS as is the Monarch-data-loaf VM. I assume that we want to load Ubuntu 16.04 LTS for the new monarch-data-load.

KVM VM run at about 98% of the base hardware speed. Quite efficient. We have a choice of using the base hardware or creating a VM for the new instance of monarch-data-load.

I'll need to drive out to the datacenter Monday to load Ubuntu 16.04 on the hardware. Then we have the option of using the hardware directly or making a VM.

The existing VM container just fits on the hardware with 2.5 GB free. A little tight... If we made a VM we would want to make it a bit under 1 TB in size.

There are advantages to using the hardware and also advantages to using a VM. 

So my current plan is to get to the datacenter monday and load 16.04 on the hardware.

**Comment by jnguyenx** [comment]
Yes, 16.04 is the way to go.

I would rather go bare metal to use all the available resources of this
machine.

Thanks!

**Comment by vanmatre** [comment]
OK, monarch5 is now running ubuntu 16.04.1 LTS. Accounts have been created for users but not services (jenkins etc). There is about 1.1 TB free.

The box is located at monarch5.cslu.ohsu.edu and is currently only accessible from on the OHSU network (i.e. from another monarch VM).

monarch-data-load has ports 80 and 443 open externally to OHSU (but not ssh) I will request that monarch5 also have those ports opened. That will take a day or few.

Please note that this physical machine appears to have lost its video display. I was not able to connect a monitor and take to the console. This will be a problem should the machine fail and need a reload from cdrom some time inthe future. It could become a brick. I assume that it is not on warrenty at this time. ...

It is all yours to start working on.

**Comment by jnguyenx** [comment]
Awesome! Thank you so much!

**Comment by jnguyenx** [comment]
@cmungall is tartini still under warranty?

**Comment by jnguyenx** [comment]
@vanmatre did you copy the users file from monarch-access? I'm not in the sudoers and the user monarch looks to have another password. Can you please double check?

**Comment by vanmatre** [comment]
Yes, users come from monarch-access. You are now in the sudo list. Sorry for the oversight

**Comment by jnguyenx** [comment]
Thanks, I installed almost all the services.

Quick question, do you have the future public IP address of that machine? We need to send the IP and ssh keys to another institution in order to have access to one of their machine.

**Comment by vanmatre** [comment]
An external address has been requested, no results yet.  - http and https access was also requested. Do you need ssh externally?

--Ethan

Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
No no ssh through monarch-acess is very fine.

Oki I'll wait, thanks for the update!

**Comment by vanmatre** [comment]
A quick follow up and we got the external address assigned (137.53.238.117) so you should be able to access it externally at that address (http/s).

What shall we call it? I assume that you do not want to switch over monarch-data-load quite yet.

We can just use the address or some other temp name.

**Comment by jnguyenx** [comment]
Yeah a temporary name is fine for now, we still need to do some work before
moving the domain name to it. tartini.monarchinitiative.org is good enough
for now.

Thanks!

**Comment by vanmatre** [comment]
OK tartini.monarchinitiative.org has been added to DNS.

**Comment by jmcmurry** [comment]
yay, thanks! :)

**Comment by jnguyenx** [comment]
@vanmatre I migrated jenkins, can you switch the subdomain ci.monarchinitiative.org to monarch5 please?

**Comment by vanmatre** [comment]
Changes made, should be good to go.

**Comment by jnguyenx** [comment]
Thanks! 

Let's keep monarch-data-load around for a bit in case there's an issue.

**Comment by TomConlin** [comment]
note: 
monarch-data-load is used for tasks other than serving jenkins so keeping it around would be good.

**Comment by jnguyenx** [comment]
@TomConlin what do you use it for?

**Comment by TomConlin** [comment]
when it is usable, everything.  
transferring large amounts of data to/from my home net is slow so I try to keep routine volume processing on mondl.  note Kent Matt, Jim and JP also use mondl (monarch-data-load) for arbitrary data processing. KS & I each are using ~150G there now
