### ISSUE TITLE
New VM request for Solr 6

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#44]
monarch-solr6-dev

Ubuntu 16.04
6 cores
32GB
750GB - 1TB disk space (not sure yet how big the data will be).

This is meant to replace monarch-solr-dev in the long run, but for now we're still experimenting.

**Comment by vanmatre** [comment]
monarch-solr6-dev is up and running. 10.95.40.135  It is in the local monarch DNS and can be accessed from the other monarch servers.

Do you need outside access to it (and which ports)?

**Comment by jnguyenx** [comment]
Yes, same as monarch-solr-dev. Port 80 and 443.

Thank you for the quick install!

**Comment by vanmatre** [comment]
No problem, Will get the external address and port request started.

**Comment by jnguyenx** [comment]
@vanmatre do we have an external address for this server on port 80? I've installed solr but don't know which IP / url to use?

**Comment by vanmatre** [comment]
Not yet. Let me check with our network folks to see whats up.

--Ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by vanmatre** [comment]
Just got the address from network engineering. It has been added to the external DNS server.

monarch-solr6.dev.monarchinitiative.org 137.53.238.116 (http and https open)

it may take a little time to become fully active but there it is.

Regards, Ethan



Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
All good for me! Might be useful to add this to the server list.

Thanks!
