### ISSUE TITLE
httpS for data.monarchinitiative.org/

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/monarch-devops#46]
https://data.monarchinitiative.org does not currently resolve.  It should for consistency with the rest of monarchinitiative.org.

**Comment by jmcmurry** [comment]
+1

**Comment by vanmatre** [comment]
I just checked  data.monarchinitiative.org - it does resolve for me from both off site (outside of ohsu's network) and internally to ohsu's network.

However, the webserver running on it appears to respond to http requests but not to https requests.

Nmap from external servers show both http and https are open. Chrome says that data exists but is not responding to https requests.

Looks like a webserver configuration issue.

**Comment by jnguyenx** [comment]
Let's wait to upgrade the OS to 16.04, letsencrypt comes packaged with that version.

**Comment by julesjacobsen** [comment]
Is this meant to be a general purpose public FTP for people to download data from? Can I use this to publish Exomsier bundles from? If so is there a preferred place? e.g http://data.monarchinitiative.org/pub/ or doesn't it really matter?

**Comment by TomConlin** [comment]
Hi @jnguyenx  data.monarchinitiative.org  is at 16.4 are you still planning to setup the letsencrypt cert

**Comment by jnguyenx** [comment]
Yep, I'm wondering if we should support both http and https, or https only. Any thoughts?

**Comment by TomConlin** [comment]
Much as I dislike abandoning a perfectly good tool (http) 
I do not expect that we have population of users who will be 
negatively impacted by our redirecting them to https.

**Comment by jnguyenx** [comment]
It should work now, I'll let you check please.

**Comment by TomConlin** [comment]
It seems to work splendidly
