### ISSUE TITLE
Monarch dataload (and other machines)  need OS updates

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/monarch-devops#48]
Logging into  monarch-data-load  (10.95.40.142)
we are greeted with:
###### #######################################

WARNING: Security updates for your current Hardware Enablement Stack
ended on 2016-08-04:
- http://wiki.ubuntu.com/1404_HWE_EOL

To upgrade to a supported (or longer-supported) configuration:
- Upgrade from Ubuntu 14.04 LTS to Ubuntu 16.04 LTS by running:
  sudo do-release-upgrade 

OR
- Switch to the current security-supported stack by running:
  sudo apt-get install linux-generic-lts-xenial linux-image-generic-lts-xenial

and reboot your system.

**Comment by TomConlin** [comment]
@vanmatre Hi Ethan, I note some of Monarch's other machines are now running 16.4; 
keeping the development and production environments as close as possible gives me warm fuzzies.

**Comment by vanmatre** [comment]
I have updated each VM and server to the current version of the initial OS load (14 or 16). Newer VM are created with 16 LTS.

I will be updating the 14 LTS OS to 16 LTS over the next 2 weeks. This will require reboots of the VM . There is a chance that the OS update will fail and turn the VM into a brick (note likely - but it does happen every once in a while).

Please advise me if there is a system that you want updated first or last or not at all. Also, I will try to give 24 hours warning.

**Comment by vanmatre** [comment]
The first systems to be updated are the physical servers - Monarch1 through monarch4. This should have minimal impact (except for a reboot). Update most likely to happen Tuesday night or wednesday morning.

**Comment by jnguyenx** [comment]
I wouldn't update the OS wildly like that, as you said there's a risk to stall our services.

In any case for the majority of the VMs we need a reinstall to have a disk space which can be stretched with LVM. That's a good opportunity to upgrade the OS at that time.

For physical servers I'll leave that up to you.

**Comment by jnguyenx** [comment]
I wouldn't update the OS wildly like that, as you said there's a risk to
stall our services.

In any case for the majority of the VMs we need a reinstall to have a disk
space which can be stretched with LVM. That's a good opportunity to upgrade
the OS at that time.

For physical servers I'll leave that up to you.

**Comment by vanmatre** [comment]
Sounds good. I'll hold off on the update till it appears to be needed.

**Comment by jnguyenx** [comment]
VMs ready to be upgraded:

- monarch-mme-prod
- gray-log
- monarch-noctua-prod
- genome (@nathandunn are you fine with Ubuntu 16.04?)
- monarch-access
- monarch-data-load
- owlsim
- ns1 (?)
- vm1-openrif (?)

VMs that need reinstall for resizable disks support:

- neo4j
- scigraph-data-prod
- scigraph-data-dev
- scigraph-ontology-prod
- scigraph-ontology-dev
- monarch-ttl-prod
- owlsim3

We'll need to synchronize later on for the VMs that need a reinstall.
I don't see any showstoppers for the VMs from the first list. I only have doubts for the last two, not sure what they're used for.

And by the way, the server list spreadsheet is getting out of date, can you please update it?

**Comment by vanmatre** [comment]
I'll see about scheduling the updates....

vm1-openrif is something that @essaids asked for.

ns1 is the internal DNS nameserver that makes internal addresses work.

I always loose track of the provision spreadsheet location. Thus updating it goes south.

**Comment by jnguyenx** [comment]
Bookmark! :-)
https://docs.google.com/spreadsheets/d/1VteU83L2rS9yHs6RlsUyZDf_-0inJ1IEfHt2FZqlNEM/edit#gid=1836081627

**Comment by vanmatre** [comment]
Got a new "build" installed on my computer the other day. Somehow I lost all my bookmarks and account information (not the builds fault really) - of the joys of corporate security.

**Comment by jnguyenx** [comment]
@vanmatre can you please reinstall:
- scigraph-data-dev (need 200GB diskspace)
- scigraph-ontology-dev

with 16.04 and resizable disk?

**Comment by vanmatre** [comment]
OK I'll put those on the next slot on the to do list. 200 GB each? My notes were looking at 500 GB

**Comment by jnguyenx** [comment]
scigraph-ontology-dev still has a lot of free disk, no need to increase it.

scigraph-data-dev is almost full at the moment. If we have enough space,
500GB sounds good (remember that we'll have to increase it for prod as well
later on). In any case we'll be more flexible with lvm.

**Comment by vanmatre** [comment]
These 2 VM have been created and are in the local DNS. The names have had a "-a" appended to them till you are ready to go live with them then I will change the name and remove the -a.

scigraph-ontology-dev-a (10.95.40.136)    6 cores, 32GB, 512 MB
scigraph-data-dev-a (10.94.40.147)  6 cores, 64GB, 512 MB

Please be aware that I have oversubscribed the number of cores so shutting down the original VM is important. I don't expect problems so long as we do not overload the base hardware.

These VM do not have external addresses. When we shut down the original VM I will not only rename these new VM but change their addresses to take the place of the original. Hopefully we do not have any "hardcoded" addresses/hostnames inline.

I planed to be out all Thanksgiving week but it looks like I will be in at least one day next week. I will check email off and on and can respond to any problems that may have come up. Just let me know and I'll get to them.

Till then....

**Comment by jnguyenx** [comment]
@vanmatre thanks! I've just finished installing the services on those machines, can you please do the swap when you can?

While you're at it, can you create scigraph-ontology-prod-a and scigraph-data-prod-a? Same specs as the ones you just created.

**Comment by vanmatre** [comment]
The swap is done. Your new VM are at the old address and names (no -a) (don't forget that the ssh key has changed)

I'll see about the other 2 vm

**Comment by jnguyenx** [comment]
Thanks, did you update the subdomain name as well in GoDaddy? I get weird stuff at the moment, my feeling is that the subdomains still point to the old VMs.

**Comment by vanmatre** [comment]
The new VM took the addresses of the old vm so the DNS (internal and godaddy) addresses do not need to change. The ssh keys do need to be updated

**Comment by jnguyenx** [comment]
Now it looks good, maybe some caches were present somewhere. Thanks!

**Comment by vanmatre** [comment]
Yes, that was my thought too. Had we worried there for a moment....

**Comment by vanmatre** [comment]
The new V have been created (using dhcp for their network addresses) but are not in DNS.

scigraph-ontology-prod-a is at 10.95.40.27
scigraph-data-prod-a is at 10.95.40.28

Feel free to load apps on them. Then I can swap them into position with the "normal" addresses.

Also let me know if you will need a DNS entry for access or if the addresses will work for now.

**Comment by jnguyenx** [comment]
Thanks, that's perfect for now. I'll install them asap!

I guess that you're out for the rest of the week, enjoy thanksgiving!

**Comment by jnguyenx** [comment]
@vanmatre what's the procedure to upgrade the OS on the VM that don't need LVM (ie a reinstall)? You take care of it or can we just run the `do-release-upgrade` command?

**Comment by vanmatre** [comment]
I have been doing the do-release-upgrade where possible. I tend to want to do that myself because sometimes it can go sideways and need some "hands-on".

Timing is everything - got one that you want me to do now?

**Comment by TomConlin** [comment]
I'm working on monarch-dataload this morning, prefer it not get yanked from under me.
the ci machine (monarch5) has another 1.3 days on a job and should stay up

**Comment by vanmatre** [comment]
That is exactly what I mean by timing - let everyone know that the machine will go down and that a new OS will be loaded with some things not working just as before.

I have no plans to bring any machine down at the moment.

**Comment by jnguyenx** [comment]
@vanmatre Ok, in that case can you please upgrade monarch-app-beta? So we can test a bit in prevision of migrating monarch-app-prod with the new scigraphs prod, hopefully by the end of the week.

**Comment by vanmatre** [comment]
Sure thing. Starting in a few moments.

**Comment by vanmatre** [comment]
It is done. monarch-app-beta is running 16.04.1

**Comment by jnguyenx** [comment]
Thanks! Note that I had to restart supervisor manually and restore the
nginx.conf. Otherwise it seems to work.

**Comment by jnguyenx** [comment]
We need to do a couple of fixes before upgrading monarch-app-prod, but I wanted to share my thoughts:

To avoid downtime, we can point monarchinitiative.org to monarch-app-beta, so we're free to upgrade monarch-app-prod and the two prod scigraph instances. And then when we're happy we can switch back the domain name.
Does it reasonable?

Is Friday a good day to do that for you?

**Comment by vanmatre** [comment]
Friday would be fine for me.

Downtime for the upgrade is less than 30 minutes for the system side of things to Ubuntu 16.04.1 and if you can stand that much down time I could do the upgrades in the wee hours of the night/morning. This assumes that our major users are from the PST timezone.

Your choice.

**Comment by jnguyenx** [comment]
It'll take a bit more time than that because I need to do some work on the
scigraph instances, like generate ssl certs, which I can only do once we
have moved the domain name.
I think that it's safer to play with the main domain name, things can go
wrong ;-)

Okay then, I'll ping you on Friday!

**Comment by vanmatre** [comment]
Friday it is. Till then

**Comment by jnguyenx** [comment]
@vanmatre I think that we can start, here are the steps I had in mind:

1. Switch monarchinitiative.org to point to monarch-app-beta
2. Test if the site still works (there might be issues with http and https)
3. Upgrade OS on monarch-app-prod and switch scigraph-*-prod-a to replace the current ones
4. Test and generate the new certs for scigraph instances
5. Switch back
6. Enjoy the weekend

**Comment by vanmatre** [comment]
Sure - remember that when switching DNS that there is a TTL lifetime before caches are updated. It will not effect a lot of accesses but it can be confusing.

Ready to begin?

**Comment by jnguyenx** [comment]
Yep!

**Comment by vanmatre** [comment]
monarchinitiative.org now points to the beta instance. There is a 500 second TTL.

**Comment by vanmatre** [comment]
I can see the site from at least one offsite (of ohsu) and what little I see shows it working.

**Comment by jnguyenx** [comment]
As I anticipated there are issues with certs, I'm looking into it.

**Comment by jnguyenx** [comment]
Okay I made the site accessible without http, that's good enough for now I guess.

We can go on with the next steps!

**Comment by vanmatre** [comment]
OK, I'll start the upgrade then do the other switch

**Comment by vanmatre** [comment]
monarch-app-prod is now upgraded to 16.01.1

scigraph-data-prod-a is now active
scigraph-ontology-prod-a is now active

DNS still points to monarch-app-dev (let me know when to swap it back to prod)

**Comment by jnguyenx** [comment]
The scigraph machines are still named with the -a at the end. Is that normal?

The dev ones have been fully renamed without the -a, it may be good to make things consistent.

**Comment by vanmatre** [comment]
I'll rename them. I keep the -a so as to not get confused as to where I am in the shuffle (it takes about 4 windows each to coordinate the change over.. But of course now is the time to change it over.

**Comment by jnguyenx** [comment]
Okay, I'm done on my side, can we try to switch back to monarch-app-prod and see what happens?

**Comment by vanmatre** [comment]
Great, DNS is switched back.

**Comment by jnguyenx** [comment]
Looks good! Thanks!

**Comment by jnguyenx** [comment]
While you're at it, can we do a reinstall of owlsim3 (nothing is running on it at the moment) and gray-log (some things are running but you can just shut them down) with lvm and ubuntu 16.04?

**Comment by vanmatre** [comment]
Sure, I'll see about that for Monday.

**Comment by vanmatre** [comment]
The new VM are up and running. Did you want me to shutdown the existing VM and move these in place before you load then?

owlsim3 10.95.40.23
gray-log 10.95.40.27

**Comment by jnguyenx** [comment]
Sure let's do the switch first, thank!

**Comment by vanmatre** [comment]
OK the old are off and the new are up and running. You all are in the sudo file.

**Comment by jnguyenx** [comment]
Excellent, only a few VMs left to upgrade!

**Comment by jnguyenx** [comment]
@vanmatre Happy new year! Let's kick off with some server upgrades, no reinstall for those, only an OS upgrade:

- monarch-mme-prod
- monarch-noctua-prod
- monarch-access
- owlsim
- genome

Let me know when you proceed, I'll keep an eye on them. Thanks!

**Comment by vanmatre** [comment]
Monarch-mme-prod is done

Monarch-access is done

Monarch-noctua is in progress but will be done RSN (real soon now)

I'll be heading out shoutly then pick up on owlsim and genome tomorrow.

**Comment by vanmatre** [comment]
They have all been updates to 16.04 at this time. Check them out to be sure all is well.

--Ethan

**Comment by jnguyenx** [comment]
Thanks will do!

**Comment by TomConlin** [comment]
monarch-data-load is up and running version 16.4  (yea!)

I do see reports of a stray file  
 
    N: Ignoring file '50unattended-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension

**Comment by vanmatre** [comment]
Yes, That is a common leftover. I usually delete them. The upgrade installed a new version and renamed the old one by adding -dist.

Causes no problems but is annoying to be reminded about it.

I'll take care of it.

--Ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
All VMs have been updated.

@vanmatre I'll let you take care of ns1 & vm1-openrif, as they're not directly used for Monarch's apps.

Thanks!
