### ISSUE TITLE
info@monarchinitiative.org e-mail address

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#5]
If I'm not mistaken, Godaddy provides either a paid hosted email service or free forwarding service.

I'd would rather use the free forwarding service and forward emails to an internal googlegroups mailing list. The downside being that we won't be able to reply with the address info@monarchinitiative.org as the sender, and we'll have to keep that address in CC when replying to an email to keep everyone in the loop.

Any thoughts @vanmatre ?

**Comment by vanmatre** [comment]
GoDaddy will allow forwarding of email. I can set that up. Just need to know the monarch email name (e.g. info) and the target email address. We can have more than one.

**Comment by jnguyenx** [comment]
duplicate #17
