### ISSUE TITLE
New VM request for Solr 6 prod

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#50]
monarch-solr6-prod

Ubuntu 16.04
6 cores
32GB
1TB disk space (do we have enough disk space still?)

Port 80 and 443 needs to be open.

This VM will replace monarch-solr-prod.

**Comment by vanmatre** [comment]
This VM has been created. DNS, Passwords and sudo all set.

Let me know if you find any problems.

**Comment by vanmatre** [comment]
externall address assigned, should be accessable now off site.

**Comment by jnguyenx** [comment]
Cool! What's the address to reach that VM?

**Comment by vanmatre** [comment]
Tartini is at 10.95.40.105

10.95.40.125  monarch2-5 solr6-prod
10.95.40.126 monarch2-6 the other VM

They should be active in dns with the correct addresses.

I'm out today but will be checking email off and on so I can check up on most things.

--Ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
Excellent, thanks!

Just a reminder to keep the googledocs up to date:
https://docs.google.com/spreadsheets/d/1VteU83L2rS9yHs6RlsUyZDf_-0inJ1IEfHt2FZqlNEM/edit#gid=1836081627

**Comment by jnguyenx** [comment]
There are some issues with server visibility, I can't use the temporary dns (i.e. monarch-solr6.dev.monarchinitiative.org) on the monarch-app-beta server, I'm forced to use the internal IPs for now. 

I think that your internal DNS server needs to be updated.

**Comment by vanmatre** [comment]
Hi,

 I took a look at the zone file and did discover a mis-type (exomizer was spelled with an s) but that does not change what you found.

I did log into monarch-app-beta and was able to log into monarch-solr6-dev. Is it a typo to call this machine monar-solr6.dev rather than monarch-solr6-dev?

I did reload the DNS zone file to be sure that any changes were active.

**Comment by jnguyenx** [comment]
Yes it's a typo, but it does not matter for now.

Once on monarch-app-beta, I need to reach monarch-solr6-dev via the monarch
domain name, such as:
monarch-app-beta:~$ curl http://monarch-solr6.dev.monarchinitiative.org
curl: (6) Could not resolve host: monarch-solr6.dev.monarchinitiative.org

It works well with the old solr server:
monarch-app-beta:~$ curl https://solr-dev.monarchinitiative.org
... some html ...

**Comment by vanmatre** [comment]
OK, good info. I'll check on what it could be.

**Comment by pnrobinson** [comment]
?btw Exomiser and Genomiser are spellt with an "s" -- we chose the UK spelling!

-Peter


Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org



The Jackson Laboratory: Leading the search for tomorrow's cures


________________________________

**Comment by jnguyenx** [comment]
Yes, exomiser with an S!

@vanmatre any update on the DNS view? It's a blocker to push things into production at the moment unfortunately.

**Comment by vanmatre** [comment]
It is changed with an "s" - DNS caches can take a TTL time to refresh but should be timed out by now. (local cacheing too)

monarch-exomiser-prod

**Comment by jnguyenx** [comment]
I mean any updates with the fact that we can't use monarch-solr6-dev external domain from monarch-app-beta?

**Comment by vanmatre** [comment]
What do you mean by external domain? Can you cive a more detailed example

 That is to say I can reach monarch-solr6-dev from monarch-app-beta. This is over the internal network. I cannot reach it through the external address. This is part of the network design.

**Comment by jnguyenx** [comment]
This example is still failing at the moment:

> monarch-app-beta:~$ curl http://monarch-solr6.dev.monarchinitiative.org
> curl: (6) Could not resolve host: monarch-solr6.dev.monarchinitiative.org
> 
> It works well with the old solr server:
> monarch-app-beta:~$ curl https://solr-dev.monarchinitiative.org
> ... some html ...

**Comment by vanmatre** [comment]
evm@monarch-app-beta:~$ curl http://monarch-solr6.dev.monarchinitiative.org
curl: (6) Could not resolve host: monarch-solr6.dev.monarchinitiative.org
evm@monarch-app-beta:~$ curl http://monarch-solr6-dev.monarchinitiative.org
.......................................................................................^

What is the name of the host? With a - it resolved but does not serve any content.

**Comment by jnguyenx** [comment]
Okay that's the other around outside OHSU network, http://monarch-solr6.dev.monarchinitiative.org resolves but http://monarch-solr6-dev.monarchinitiative.org does not.
That's normal if the server content is empty.

Sounds like the url needs to be fixed somewhere, GoDaddy I presume?

**Comment by vanmatre** [comment]
Ah.... So the typo is that externally monarch-solr6.dev resolves and it should be monarch-solr6-dev. That would be my typo.

Poof, (orange smoke dissapates slowly) it is changed in godaddy to monarch-solr6-dev

**Comment by jnguyenx** [comment]
That works better now! Thanks!

Our trouble are not done yet:
Can you please point solr-dev.monarchinitiative.org to this monarch-solr6-dev please?

**Comment by vanmatre** [comment]
Done in both the internal DNS and Godaddy.

**Comment by jnguyenx** [comment]
Perfect thank you! I'll ping you when we're ready to migrate the solr6 prod.

**Comment by jnguyenx** [comment]
@vanmatre can you please switch solr.monarchinitiative.org to point to monarch-solr6-prod?

**Comment by vanmatre** [comment]
solr.monarchinitiative.org now points to monarch-solr6-prod (both internal DNS and external DNS)

monarch-solr-prod still points to the solr VM and monarch-solr6-prod still points to the solr6 VM.

**Comment by jnguyenx** [comment]
Awesome! Thanks!
