### ISSUE TITLE
New VM request for Exomiser

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#51]
monarch-exomiser-prod

Ubuntu 16.04
4 cores
4GB
100GB disk space

Port 80 and 443 needs to be open.

This VM is for @julesjacobsen to install a monarch instance of exomiser.

**Comment by vanmatre** [comment]
This VM has been created. DNS, Passwords and sudo all set.

Let me know if you find any problems.

**Comment by kshefchek** [comment]
In running exomiser, we will likely need to load PHI on to the server.  @vanmatre are there any special considerations in doing this?  I assume there is a process we need to go through.

**Comment by vanmatre** [comment]
Yes, there a number of requirements needed to get approval to have PHI on a server. I'll start looking into what we need to do. Till then I would advise not loading any PHI.

**Comment by kshefchek** [comment]
Okay, I may be misunderstanding the requirements for this VM, but I do know we have a few of projects where we are starting to work with PHI, and it would be nice to utilize the resources on the monarch servers.  For example, the monarch-data-load would be an ideal candidate for this analysis once we move jenkins to Tartini.  @vanmatre thank you for looking into this!

**Comment by cmungall** [comment]
What are the rules for doing this on EC2?

**Comment by kshefchek** [comment]
We'll likely need to consult with the UDN/UDP to see if this is an option.

**Comment by vanmatre** [comment]
external access is assigned it should be in dns now and accessable

**Comment by kshefchek** [comment]
@vanmatre we are going to consider alternatives to process PHI data (amazon, exacloud), so we can hold off on investigating requirements for the monarch servers.

**Comment by vanmatre** [comment]
No problem - we can tackle that "hill" at a later date
