### ISSUE TITLE
monarch-solr-dev and monarch-solr-prod decommissioning

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#52]
Now with the beta and prod running on the new solr6 machines, I don't think that we need those VMs anymore. As a safety measure we can make a snapshot and keep them around, even though I don't think that it is necessary.

**Comment by vanmatre** [comment]
Monarch-solr-prod shutdown

Monarch-solr-dev shutdown

I'll keep the container file more or less forever....
