### ISSUE TITLE
New VM api.monarchinitiative.org

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#57]
name: monarch-api
Ubuntu 16.04
2 core
2GB
20GB disk space

**Comment by vanmatre** [comment]
monach-api is up and running, in DNS, with accounts and sudo. Give it a try. 

Let me know if you need external access or if there are port problems.

**Comment by jnguyenx** [comment]
I can't ssh in, my username or pwd are not recognized.

**Comment by vanmatre** [comment]
Now try it

**Comment by jnguyenx** [comment]
It works now, but it seems that the VM cannot access internet, for example
apt-get update does not work.

**Comment by vanmatre** [comment]
Took a second for our networking to figure the VM existed - I can now ping google.com and to an apt-get update/upgrade

**Comment by jnguyenx** [comment]
Excellent! Thank you so much.

**Comment by vanmatre** [comment]
Not a problem. Have fun

**Comment by jnguyenx** [comment]
@vanmatre I think that I have DNS issues, I can't reach the machine with http://api.monarchinitiative.org/ or http://monarch-api.monarchinitiative.org/.

I do have a webserver running on port 80:

```
monarch-api:~$ curl http://localhost
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by vanmatre** [comment]
Ah, outside access needed. I can readdress monarch-api to an address that has an existing outside IP assigned to it. This will cut a few days off getting an outside address assigned.

I can reboot it now if that will not cause any problems with the python script running

**Comment by jnguyenx** [comment]
Sure go for it!

**Comment by vanmatre** [comment]
It is back up at the new address. The names have not changed...

I get a 502 Bad Gateway from nginx from outside the ohsu network. So it is at least responding on port 80.

Let me know what else is needed from my end

**Comment by jnguyenx** [comment]
Cool! Can we also have api.monarchinitiative.org pointing to that server?

**Comment by vanmatre** [comment]
Done! the cname is active (api.monarchinitiative.org)

**Comment by jnguyenx** [comment]
Thanks! I'll stop bugging you for this year, happy holidays!
