### ISSUE TITLE
Subdomain request for the Monarch Journal Annotator

### ISSUE THREAD

**Issue by tudorgroza** [monarch-initiative/monarch-devops#58]
Hi,

Can we please set up a subdomain for the Monarch Journal Annotator? (jannotator.monarch .... perhaps?)

Thanks,
T

**Comment by jnguyenx** [comment]
Sure, where should it point to exactly?

**Comment by tudorgroza** [comment]
@jnguyenx - apologies for the delayed response. Please point it to: 43.240.98.24. Thanks.

**Comment by mellybelly** [comment]
what is the status of this?

**Comment by vanmatre** [comment]
Completed

**Comment by vanmatre** [comment]
At least the DNS end of it is.

**Comment by genome-one** [comment]
Up and running. Thank you!
