### ISSUE TITLE
http://api.monarchinitiative.org/ no longer reflects github master

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-devops#64]
Recently I moved 

https://github.com/monarch-initiative/biolink-api/

to

https://github.com/biolink/biolink-api

I then make a fork of biolink/biolink-api in monarch-initiative

The intent is that the monarch api instance should always reflect what in the monarch org repo

However, in doing this I obviously broke something, and api.monarchinitiative.org no longer reflects master. As an example, the api version at the bottom should now be 1.1.1, rather than just 1.1

**Comment by jnguyenx** [comment]
Done! You'll need to accept my PR https://github.com/biolink/biolink-api/pull/24, I had to modify the start script.

**Comment by jnguyenx** [comment]
Actually I need to check the webhooks of the git repo as well, can you add me as admin please?

**Comment by jnguyenx** [comment]
Should be all good!
