### ISSUE TITLE
Run with biolink api multiple worker threads

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-devops#70]
From: http://gunicorn-docs.readthedocs.io/en/latest/design.html
'Generally we recommend (2 x $num_cores) + 1 as the number of workers to start off with'

I think means adding:

```
-k gevent --worker-connections NN
```

You'll need to add gevent to requirements.txt

Can alternately be done with multiple threads, e.g. `-w 10`, but I think the above is better

**Comment by jnguyenx** [comment]
https://github.com/biolink/biolink-api/commit/f3dd413d3832750fb02f6c0d81cb9cdd45e69d4e
