### ISSUE TITLE
New VM request for exomiser-web-dev

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/monarch-devops#73]
monarch-exomiser-web-dev
Ubuntu 16.04
8 cores
8GB
100GB disk space
Port 80 and 443 needs to be open.

This VM is for the monarch dev instance of exomiser-web.

**Comment by vanmatre** [comment]
Working on it.

**Comment by vanmatre** [comment]
monarch-exomiser-web-dev has been created - please log when you are ready.

--Ethan

**Comment by jnguyenx** [comment]
Ethan, I don't know if it is related or if I should open another issue, but
I cannot ssh in the machines using the short names:

```
@monarch-access:~$ ssh scigraph-data-dev
ssh: Could not resolve hostname scigraph-data-dev: Temporary failure in
name resolution
```

**Comment by vanmatre** [comment]
From where are you trying the short names? If locally on one of the monarch machines then the search primitive inthe resolver is likely not working.

--Ethna


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
From monarch-access, you can see it from the snippet.

It seems that none of the short names are working, must be the resolved
which has some issues.

**Comment by vanmatre** [comment]
Looks like the local nameserver has failed. I'm looking into it.



Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by vanmatre** [comment]
Got it. should be working now. I just introduced a typo inthe zone file and it failed without an obvious error message.



Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
All good, thanks!

**Comment by vanmatre** [comment]
no problem!


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by julesjacobsen** [comment]
I can access the machine, thanks for the speedy work.
