### ISSUE TITLE
VMs shuffling

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#76]
2 services will need proper dev and prod environment.

Rename, but keep domain name as it is:
```
monarch-api -> monarch-api-prod
owlsim3 -> owlsim3-prod
```

new VMs, with *-dev.monarchinitiative.org domain name and same specs as the prod ones.
```
monarch-api-dev
owlsim3-dev
```

**Comment by vanmatre** [comment]
OK, so to be sure what you want the steps are:

1) rename the VM api to api-prod
2) rename the VM owlsim3 to owlsim3-prod

3) create new VM api-dev
4) create new VM owlsim3-dev

5) DNS api-prod points to VM api-prod
6) DNS owlsim3-prod points to VM owlsim3-prod

7) DNS api CNAME points to api-prod VM
8) DNS owlsim3 CNAME points to owlsim3-prod VM

9) DNS api-dev points to api-dev VM
10) DNS owlsim3-dev points to owlsim3-dev VM

OK can do.

**Comment by vanmatre** [comment]
I notice the the actual host name of api is monarch-api. Shall I change it to monarch-api-prod or to api-prod?

**Comment by jnguyenx** [comment]
yes, you got it right!

oh ok, let's keep it with monarch-api then, I'll update the issue.

Thanks!

**Comment by vanmatre** [comment]
Will do. I can do the renames and dns today and the new vm creation on monday,

**Comment by jnguyenx** [comment]
That works, thanks.

**Comment by vanmatre** [comment]
Internal and external DNS changes made and tested. Remember that your DNS reesolver may cache addresses for up to 4 hours or so.

I'll check my email later tonight just in case anyone discovers a problem and emails me with it (rather than take a full weekend to get to it).

**Comment by jnguyenx** [comment]
From what I can tell, the renaming worked. Thanks!

**Comment by vanmatre** [comment]
owlsim3-dev and monarch-api-dev are up and ready to provision. They have internal (to ohsu) addresses. Do we need outside (of ohsu) access to then with ssh, http, https ?

**Comment by jnguyenx** [comment]
Cool! Yes we'll need http and https please. Thanks!

**Comment by vanmatre** [comment]
I should note that the CPU are oversubscribed on the physical hardware. I have retired vm1-openrif (an unused vm) to free up a few cores.

I do not expect there to be a great impact because we rarely peg all of the cores.

**Comment by vanmatre** [comment]
I'll get the request for setting up the external addresses going - it will take a few days. Till then you can access these VM from an ssh tunnel through monarch-access....

**Comment by jnguyenx** [comment]
Perfect thank you!

**Comment by jnguyenx** [comment]
@vanmatre Can you add a subdomain api-dev.monarchinitiative.org to monarch-api-dev please?

**Comment by vanmatre** [comment]
I've added a CNAME record to the internal and external DNS servers. api-dev now points to monarch-api-dev.

--Ethan

PS

In domain namespace the leftmost part is the host name. monarchinitiative.org is the domain and monarch-api-dev.monarchinitiative.org is a FQDN (fully qualified domain name) where monarch-api-dev is the host name. We can create an "alias" in the form of a CNAME (cannonical name) thus api-dev.monatchinitiative.org is a pointer to monarch-api-dev.monarchinitiative.org.

A subdomain is a child domain of a parent domain. To create a new monarch subdomain "test" we would end up with a (sub)domain test.monarchinitiative.org. And that subdomain could be populated with hosts:
 monarch-api-dev.test.monarchinitiative.org and so on.

Just food for thought....

Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
Awsome!
