### ISSUE TITLE
Spark + Zeppelin VMs

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#77]
**spark-master**
Ubuntu 16.04
2 cores
4GB
100GB disk space
Port 80 and 443 needs to be open.
spark-master.monarchinitiative.org

**spark-slave1**
Ubuntu 16.04
16 cores
64GB
1TB disk space
Port 80 and 443 needs to be open.
spark-slave1.monarchinitiative.org

**zeppelin**
Ubuntu 16.04
4 cores
8GB
1TB disk space
Port 80 and 443 needs to be open.
zeppelin.monarchinitiative.org

**Comment by vanmatre** [comment]
Starting to work on this. Be aware that we are oversubscribed in CPU and memory.

**Comment by vanmatre** [comment]
These 3 VM have all been created, loaded into internal and external DNS, Users added and sudo set.

They should all be ready to go with external access to 80 and 443

External address have also been conigured for owlsim3-dev and monarch-api-dev.

Regards, Ethan

**Comment by jnguyenx** [comment]
Thanks!

**Comment by jnguyenx** [comment]
Note that `spark-slave1` is actually named `spark-slave`, not a big deal though.

**Comment by vanmatre** [comment]
I can change that - shall I?

**Comment by jnguyenx** [comment]
Hmmm I'm tempted... let's do it! So it'll be easier in the future to add numbered slaves.

**Comment by vanmatre** [comment]
There, that should cover it. Now named spark-slave1

**Comment by jnguyenx** [comment]
All good, thanks!
