### ISSUE TITLE
Install graylog

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#9]

**Comment by kshefchek** [comment]
cc @TomConlin 

@jnguyenx please add an account for Tom when you set this up.

**Comment by vanmatre** [comment]
Tom has an account on all servers including gray log

--Ethan

**Comment by TomConlin** [comment]
Thanks Ethan, would it be possible to get a list of what all the servers are, and work out a sensible way to communicate initial passwords?

**Comment by vanmatre** [comment]
Hi Tom,

 Take a look at the hosts file for an easy way to get the server list.

 I'm a shared resource but as time allows I am putting in an LDAP server for single logins.  To start with I've copied the password from monarch-access to the various other machines. LDAP will be sensible.


I'm heading off to a meeting at 11 but can help you get started in an hour.

-_Ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
I think that setting up the LDAP server is a very low priority task. It'll
more useful to have the DNS views or setting up the Nagios notifications.

Concerning the servers list we have this reference document:
https://docs.google.com/spreadsheets/d/1VteU83L2rS9yHs6RlsUyZDf_-0inJ1IEfHt2FZqlNEM/edit#gid=168336483

**Comment by jnguyenx** [comment]
gray-log.monarchinitiative.org
